image:
  file: .gitpod.dockerfile

ports:
- port: 8080
- port: 5000-5999
  onOpen: ignore

tasks:
- init: |
    cd /workspace/extension-registry/webui
    yarn
    yarn build:dev
    cd /workspace/extension-registry/server
    ./gradlew build downloadTestExtensions -x buildNative -x testNative
  command: |
    cd /workspace/extension-registry/server
    ./gradlew quarkusDev
- command: |
    cd /workspace/extension-registry/server
    gp await-port 8080
    find build/test-extensions -name '*.vsix' -exec ./publish.sh '{}' \;
